---
resources:
- name: docker-repo
  type: git
  source:
    uri: https://github.com/EngineerBetter/cf-terraform-image
    branch: master
    ignore_paths:
    - ci/version

- name: terraform-provider-cloudfoundry
  type: github-release
  source:
    owner: orange-cloudfoundry
    repository: terraform-provider-cloudfoundry
    access_token: ((api_token))

- name: cf-terraform-image-dockerhub
  type: docker-image
  source:
    repository: engineerbetter/cf-terraform-image
    username: ((docker_username))
    password: ((docker_password))

- name: terraform-docker-image
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:EngineerBetter/cf-terraform-image.git
    branch: master
    file: ci/version
    private_key: ((version_deploy_key))

jobs:
- name: build-image
  serial: true
  plan:
  - aggregate:
    - get: docker-repo
      trigger: true
    - get: terraform-provider-cloudfoundry
      trigger: true
      params:
        globs:
        - terraform-provider-cloudfoundry_*_linux_amd64
    - get: terraform-docker-image
      trigger: true
    - get: version
  - task: prepare-files
    image: terraform-docker-image
    config:
      platform: linux
      inputs:
      - name: docker-repo
      - name: terraform-provider-cloudfoundry
      outputs:
      - name: docker
      run:
        path: sh
        args:
          - -xeuc
          - |
            mkdir -p docker
            mv docker-repo/assets/* docker/
            mv docker-repo/assets/.terraformrc docker/
            mv terraform-provider-cloudfoundry/terraform-provider-cloudfoundry_*_linux_amd64 docker/terraform-provider-cloudfoundry
  - put: cf-terraform-image-dockerhub
    params:
      build: docker
      tag: version/version
      tag_as_latest: true
  - put: version
    params:
      bump: patch
