---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: docker-repo
  type: git
  source:
    uri: https://github.com/EngineerBetter/cf-terraform-image
    branch: master
    paths:
    - assets
    ignore_paths:
    - ci/version

- name: terraform-provider-cf
  type: github-release
  source:
    owner: mevansam
    repository: terraform-provider-cf
    access_token: ((github_access_token))

- name: cf-terraform-image-dockerhub
  type: docker-image
  source:
    repository: engineerbetter/cf-terraform-image
    username: ((docker_username))
    password: ((docker_password))

- name: terraform-docker-image
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:EngineerBetter/cf-terraform-image.git
    branch: master
    file: ci/version
    private_key: ((version_deploy_key.private_key))

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack_webhook))

jobs:
- name: build-image
  serial: true
  plan:
  - aggregate:
    - get: docker-repo
      trigger: true
    - get: terraform-provider-cf
      trigger: true
      params:
        globs:
        - terraform-provider-cf_linux_amd64
    - get: terraform-docker-image
      trigger: true
    - get: version
      params:
        bump: patch
  - task: prepare-files
    image: terraform-docker-image
    config:
      platform: linux
      inputs:
      - name: docker-repo
      - name: terraform-provider-cf
      outputs:
      - name: docker
      run:
        path: sh
        args:
          - -xeuc
          - |
            mkdir -p docker
            mv docker-repo/assets/* docker/
            mv docker-repo/assets/.terraformrc docker/
            mv terraform-provider-cf/terraform-provider-cf_linux_amd64 docker/terraform-provider-cf
  - put: cf-terraform-image-dockerhub
    params:
      build: docker
      tag: version/version
      tag_as_latest: true
  - put: version
    params:
      bump: patch
  - put: slack-alert
    params:
      channel: "#integrations"
      text: |
        Version v${TEXT_FILE_CONTENT} of the cf-terraform-image has been pushed to dockerhub!
      text_file: version/version
